Django/practice/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
]

Django/practice/practice/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

Django/practice/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    title_en = models.CharField(max_length=50)
    audience = models.CharField(max_length=20)
    open_date = models.CharField(max_length=20)
    genre = models.CharField(max_length=20)
    watch_grade = models.CharField(max_length=10)
    score = models.CharField(max_length=10)
    poster_url = models.CharField(max_length=500)
    description = models.TextField()
    

Django/practice/movies/views.py
from django.shortcuts import render
from .models import Movie

# Create your views here.

def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,

    }
    return render(request,'movies/index.html', context)

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'title': title,
        'title_en': title_en,
        'audience': audience,
        'open_date': open_date,
        'genre': genre, 
        'watch_grade': watch_grade,
        'score': score,
        'poster_url': poster_url,
        'description': description,

    }
    return render(request, 'movies/detail.html', context)

Django/practice/movies/templates/movies/detail.html
{% extends 'base.html' %}


{% block body %}

<h1>Movie Detail</h1>

<p>PK: {{ movie.pk }} </p>
<p>제목: {{ movie.title }}</p>
<p>영어 제목: {{ movie.title_en }}</p>
<p>관객 수: {{ movie.audience }}</p>
<p>개봉일: {{ movie.open_date }}</p>
<p>상영 등급: {{ movie.watch_grade }}</p>
<p>평점: {{ movie.score }}</p>
<p>영화 포스터: {{ movie.poster_url }}</p>
<p>개요: {{ movie.description }}</p>



{% endblock %}

Django/practice/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>Movie Index</h1>

    <ul>
        {% for movie in movies %}
        <li>
            <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a>
            {{ movie.score }}
        </li>

        {% endfor %}
    </ul>
{% endblock %}

Django/practice/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body%}
    {% endblock %}
</body>
</html>