Django/visitors/visitors/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('visitors/', include('visitors_data.urls')),
    path('', lambda r:redirect('visitors_data:home'), name='home')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/visitors/visitors_data/urls.py
from django.urls import path
from. import views

app_name = 'visitors_data'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('citizen/', views.citizen, name='citizen'),
    path('foreigner/', views.foreigner, name='foreigner'),
    # path('new/', views.new, name='new'),
    path('confirm/<int:pk>/', views.confirm, name='confirm'),
    path('qr/<int:pk>/', views.qr, name='qr'),
    path('read_qr/', views.read_qr, name='read_qr'),

]

Django/visitors/visitors_data/models.py
from django.db import models
from django.core.exceptions import ValidationError
# from .validators import validate_number


# Create your models here.
class Visitor(models.Model):
    name = models.CharField(max_length=5)
    number = models.CharField(max_length=11)
    number2 = models.CharField(max_length=11)
    date = models.DateTimeField(auto_now_add=True)
    check = models.CharField(max_length=10, default='FALSE')
    image = models.FileField()
    


# def number_validator(self):
#     number = self.number
#     number2 = self.number2
    
#     if number != number2:
#         msg = '전화번호를 다시 확인해주세요'
#         raise ValidationError(msg)
        
        

Django/visitors/visitors_data/forms.py
from django import forms
from .models import Visitor
from django.core.exceptions import ValidationError

class VisitorForm(forms.ModelForm):
    class Meta:
        model = Visitor
        fields = ('name', 'number', 'number2',)
        widgets = {'name': forms.TextInput(
                        attrs={
                            'placeholder': '홍길동',
                    }),
                    'number': forms.NumberInput(
                        attrs={
                            'placeholder': '01012345678',
                        }),
                    'number2': forms.NumberInput(
                        attrs={
                            'placeholder': '01012345678',
                        }),
        }
        labels = {
            'name': '이름',
            'number': '전화번호',
            'number2': '전화번호 확인',
        }
    
    def clean(self):
        number = self.cleaned_data.get('number')
        number2 = self.cleaned_data.get('number2')
        
        if number != number2:
            msg = '전화번호를 다시 확인해주세요'
            raise ValidationError(msg)
        
    

Django/visitors/visitors_data/views.py
from django.shortcuts import render, redirect
from .models import Visitor
import qrcode
from .forms import VisitorForm
import cv2
import re

# Create your views here.

def home(request):
    context = {

    }
    return render(request, 'visitors_data/home.html', context)

# def create(request):
#     if request.method == 'POST':
#         form = ArticleForm(request.POST)
#         if form.is_valid():
#             form.save()
#     else:
#         form = ArticleForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'articles/form.html', context)

def citizen(request): # POST
    if request.method == 'POST':
        form = VisitorForm(request.POST)
        if form.is_valid():
            # visitor = form.save()
            visitor = form.save()
            return redirect('visitors_data:confirm', visitor.pk)
    else:
        form = VisitorForm()
    context = {
        'form': form,
    }
    return render(request, 'visitors_data/citizen.html', context)

## https://docs.djangoproject.com/en/3.0/ref/contrib/messages/    => error message custom

def foreigner(request): # POST
    # if request.method == 'POST':
    #     name = request.POST.get('name')
    #     number = request.POST.get('number')

    #     visitor = Visitor(name=name, number=number)
    #     visitor.save()
    
    #     return redirect('visitors_data:detail', visitor.pk)

    # else:
    context = {

    }
    return render(request, 'visitors_data/foreigner.html', context)

def confirm(request, pk):
    visitor = Visitor.objects.get(pk=pk)
    context = {
        'visitor': visitor,

    }
    
   
    return render(request, 'visitors_data/confirm.html', context)

def qr(request, pk):
    visitor = Visitor.objects.get(pk=pk)
    qr = qrcode.QRCode(version=2, error_correction=qrcode.constants.ERROR_CORRECT_H)
    info = visitor.name + '/' + visitor.number + '/' + 'PK:' + str(visitor.pk)
    qr.add_data(info)
    qr.make
    img = qr.make_image(fill_color='black', back_color='white')
    img.save('./static/images/qrcode.png', format='PNG')

    return render(request, 'visitors_data/qr.html')

def read_qr(request):

    img = cv2.imread('./static/images/qrcode.png')
    detector = cv2.QRCodeDetector()
    data, bbox, straight_qrcode = detector.detectAndDecode(img)

    
    # video

    # import cv2
    # # initalize the cam
    # cap = cv2.VideoCapture(0)
    # # initialize the cv2 QRCode detector
    # detector = cv2.QRCodeDetector()
    # while True:
    #     _, img = cap.read()
    #     # detect and decode
    #     data, bbox, _ = detector.detectAndDecode(img)
    #     # check if there is a QRCode in the image
    #     if bbox is not None:
    #         # display the image with lines
    #         for i in range(len(bbox)):
    #             # draw all lines
    #             cv2.line(img, tuple(bbox[i][0]), tuple(bbox[(i+1) % len(bbox)][0]), color=(255, 0, 0), thickness=2)
    #         if data:
    #             print("[+] QR Code detected, data:", data)
    #     # display the result
    #     cv2.imshow("img", img)    
    #     if cv2.waitKey(1) == ord("q"):
    #         break
    # cap.release()
    # cv2.destroyAllWindows()

    # PK 추출
    p = re.compile("P+K+[:]+[0-9]+")
    pk_number = p.findall(data)[0]

    p1 = re.compile("[0-9]+")
    current_pk = p1.findall(pk_number)[0]

    # DB 수정 (check='TRUE')
    visitor = Visitor.objects.get(pk=current_pk)
    visitor.check = "TRUE"
    visitor.save()

    context = {

    }
    return render(request, 'visitors_data/read_qr.html', context)

Django/visitors/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

Django/visitors/visitors_data/templates/visitors_data/citizen.html
{% extends 'base.html' %}

{% block body%}


<h1>새로운 방문자</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="완료">
    
</form>


{% endblock %}

Django/visitors/visitors_data/templates/visitors_data/confirm.html
{% extends 'base.html' %}

{% block body %}

    <h1>이름: {{ visitor.name }}</h1>
    <h1>전화번호: {{ visitor.number }}</h1>

    <a href="{% url 'visitors_data:qr' visitor.pk %}">확인</a>

    



{% endblock %}

Django/visitors/visitors_data/templates/visitors_data/foreigner.html
{% extends 'base.html' %}

{% block body%}


<h1>New Visitor</h1>

<form action="{% url 'visitors_data:confirm' %}" method="GET">
    <label for="name">Name</label>
    <input id="name" type="text" name="name">
    <label for="number">Phone Number</label>
    <input id="number" type="int" name="number">
    <input type="submit" value="Complete">
</form>


{% endblock %}

Django/visitors/visitors_data/templates/visitors_data/home.html
{% extends 'base.html' %}

{% block body %}

<h1>Welcome</h1>

<a href="{% url 'visitors_data:citizen' %}">내국인</a>
<a href="{% url 'visitors_data:foreigner' %}">Foreigner</a>



{% endblock %}

Django/visitors/visitors_data/templates/visitors_data/qr.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<h1>QR코드 생성 완료</h1>

<img src="{% static 'images/qrcode.png' %}" alt="qrcode">


{% endblock %}

Django/visitors/visitors_data/templates/visitors_data/read_qr.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<h1>QR코드 체크</h1>



{% endblock %}